# Generated by Django 3.1.1 on 2020-09-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='reminder',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
